allowBuilds:
  '@nestjs/core': set this to true or false
  '@prisma/engines': set this to true or false
  '@scarf/scarf': set this to true or false
  prisma: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@nestjs/common@11.1.24'
  - '@nestjs/core@11.1.24'
  - '@nestjs/platform-express@11.1.24'
  - '@nestjs/testing@11.1.24'
